const mongoose = require('mongoose'); 

const noteSchema = new mongoose.Schema({
    title: {
        required: [true, "Title required for note"],
        type: String
    }, 
    image: {
        type: String,
        default: 'image-url' // Find default image url 
    }, 
    composition: [], 
    category: String, 
    review: String
})

const Note = mongoose.model('Note', noteSchema);    // Compiling the model

module.exports = Note; 

// title --> required STRING
// image --> STRING (url) maybe have a default 
// id --> auto-generated by mongo (no need to specify this)
// components/composition --> ARRAY 
// category --> STRING
// review --> STRING 